apiVersion: v1
kind: Service
metadata:
  name: opencrowd-backend
  labels:
    {{- include "opencrowd.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: opencrowd-backend
